rm(list=ls())
setwd("//Rsgnscsv1/f/Models/ETC/data/trackData/v04/")

# Capella
ls()
load("V04.Th11.1975100100.1976033123.Rdata")
i <- match(40,unlist(lapply(track,function(x) x$id)))
str(track[[i]],1)
long <- unlist(lapply(track[i], function(x) x$lon))
lati <- unlist(lapply(track[i], function(x) x$lat))
date <- unlist(lapply(track[i], function(x) x$tim))
data1 <- data.frame(Event = as.integer(1), Name = "Capella", Time = date, Longitude = long, Latitude = lati)
rm(latGrid,lonGrid,track)
rm(i,long,lati,date)

# StormO
ls()
load("V04.Th11.1981100100.1982033123.Rdata")
i <- match(36,unlist(lapply(track,function(x) x$id)))
str(track[[i]],1)
long <- unlist(lapply(track[i], function(x) x$lon))
lati <- unlist(lapply(track[i], function(x) x$lat))
date <- unlist(lapply(track[i], function(x) x$tim))
data2 <- data.frame(Event = as.integer(2), Name = "StormO", Time = date, Longitude = long, Latitude = lati)
rm(latGrid,lonGrid,track)
rm(i,long,lati,date)
total <- rbind(data1,data2)
rm(data1,data2)

# 1987J
ls()
load("V04.Th11.1987100100.1988033123.Rdata")
i <- match(8,unlist(lapply(track,function(x) x$id)))
str(track[[i]],1)
long <- unlist(lapply(track[i], function(x) x$lon))
lati <- unlist(lapply(track[i], function(x) x$lat))
date <- unlist(lapply(track[i], function(x) x$tim))
data2 <- data.frame(Event = as.integer(3), Name = "1987J", Time = date, Longitude = long, Latitude = lati)
rm(latGrid,lonGrid,track)
rm(i,long,lati,date)
total <- rbind(total,data2)
rm(data2)

# Daria
ls()
load("V04.Th11.1989100100.1990033123.Rdata")
i <- match(60,unlist(lapply(track,function(x) x$id)))
str(track[[i]],1)
long <- unlist(lapply(track[i], function(x) x$lon))
lati <- unlist(lapply(track[i], function(x) x$lat))
date <- unlist(lapply(track[i], function(x) x$tim))
data2 <- data.frame(Event = as.integer(4), Name = "Daria", Time = date, Longitude = long, Latitude = lati)
rm(latGrid,lonGrid,track)
rm(i,long,lati,date)
total <- rbind(total,data2)
rm(data2)

# Herta
ls()
load("V04.Th11.1989100100.1990033123.Rdata")
i <- match(65,unlist(lapply(track,function(x) x$id)))
str(track[[i]],1)
long <- unlist(lapply(track[i], function(x) x$lon))
lati <- unlist(lapply(track[i], function(x) x$lat))
date <- unlist(lapply(track[i], function(x) x$tim))
data2 <- data.frame(Event = as.integer(5), Name = "Herta", Time = date, Longitude = long, Latitude = lati)
rm(latGrid,lonGrid,track)
rm(i,long,lati,date)
total <- rbind(total,data2)
rm(data2)

# Vivien
ls()
load("V04.Th11.1989100100.1990033123.Rdata")
i <- match(86,unlist(lapply(track,function(x) x$id)))
str(track[[i]],1)
long <- unlist(lapply(track[i], function(x) x$lon))
lati <- unlist(lapply(track[i], function(x) x$lat))
date <- unlist(lapply(track[i], function(x) x$tim))
data2 <- data.frame(Event = as.integer(6), Name = "Vivien", Time = date, Longitude = long, Latitude = lati)
rm(latGrid,lonGrid,track)
rm(i,long,lati,date)
total <- rbind(total,data2)
rm(data2)

# Wiebke
ls()
load("V04.Th11.1989100100.1990033123.Rdata")
i <- match(87,unlist(lapply(track,function(x) x$id)))
str(track[[i]],1)
long <- unlist(lapply(track[i], function(x) x$lon))
lati <- unlist(lapply(track[i], function(x) x$lat))
date <- unlist(lapply(track[i], function(x) x$tim))
data2 <- data.frame(Event = as.integer(7), Name = "Wiebke", Time = date, Longitude = long, Latitude = lati)
rm(latGrid,lonGrid,track)
rm(i,long,lati,date)
total <- rbind(total,data2)
rm(data2)

# Verena
ls()
load("V04.Th11.1992100100.1993033123.Rdata")
i <- match(58,unlist(lapply(track,function(x) x$id)))
str(track[[i]],1)
long <- unlist(lapply(track[i], function(x) x$lon))
lati <- unlist(lapply(track[i], function(x) x$lat))
date <- unlist(lapply(track[i], function(x) x$tim))
data2 <- data.frame(Event = as.integer(8), Name = "Verena", Time = date, Longitude = long, Latitude = lati)
rm(latGrid,lonGrid,track)
rm(i,long,lati,date)
total <- rbind(total,data2)
rm(data2)

# Anatol
ls()
load("V04.Th11.1999100100.2000033123.Rdata")
i <- match(41,unlist(lapply(track,function(x) x$id)))
str(track[[i]],1)
long <- unlist(lapply(track[i], function(x) x$lon))
lati <- unlist(lapply(track[i], function(x) x$lat))
date <- unlist(lapply(track[i], function(x) x$tim))
data2 <- data.frame(Event = as.integer(9), Name = "Anatol", Time = date, Longitude = long, Latitude = lati)
rm(latGrid,lonGrid,track)
rm(i,long,lati,date)
total <- rbind(total,data2)
rm(data2)

# Lothar
ls()
load("V04.Th11.1999100100.2000033123.Rdata")
i <- match(65,unlist(lapply(track,function(x) x$id)))
str(track[[i]],1)
long <- unlist(lapply(track[i], function(x) x$lon))
lati <- unlist(lapply(track[i], function(x) x$lat))
date <- unlist(lapply(track[i], function(x) x$tim))
data2 <- data.frame(Event = as.integer(10), Name = "Lothar", Time = date, Longitude = long, Latitude = lati)
rm(latGrid,lonGrid,track)
rm(i,long,lati,date)
total <- rbind(total,data2)
rm(data2)

# Martin
ls()
load("V04.Th11.1999100100.2000033123.Rdata")
i <- match(66,unlist(lapply(track,function(x) x$id)))
str(track[[i]],1)
long <- unlist(lapply(track[i], function(x) x$lon))
lati <- unlist(lapply(track[i], function(x) x$lat))
date <- unlist(lapply(track[i], function(x) x$tim))
data2 <- data.frame(Event = as.integer(11), Name = "Martin", Time = date, Longitude = long, Latitude = lati)
rm(latGrid,lonGrid,track)
rm(i,long,lati,date)
total <- rbind(total,data2)
rm(data2)

# Jeanett
ls()
load("V04.Th11.2002100100.2003033123.Rdata")
i <- match(11,unlist(lapply(track,function(x) x$id)))
str(track[[i]],1)
long <- unlist(lapply(track[i], function(x) x$lon))
lati <- unlist(lapply(track[i], function(x) x$lat))
date <- unlist(lapply(track[i], function(x) x$tim))
data2 <- data.frame(Event = as.integer(12), Name = "Jeanett", Time = date, Longitude = long, Latitude = lati)
rm(latGrid,lonGrid,track)
rm(i,long,lati,date)
total <- rbind(total,data2)
rm(data2)

# Erwin
ls()
load("V04.Th11.2004100100.2005033123.Rdata")
i <- match(69,unlist(lapply(track,function(x) x$id)))
str(track[[i]],1)
long <- unlist(lapply(track[i], function(x) x$lon))
lati <- unlist(lapply(track[i], function(x) x$lat))
date <- unlist(lapply(track[i], function(x) x$tim))
data2 <- data.frame(Event = as.integer(13), Name = "Erwin", Time = date, Longitude = long, Latitude = lati)
rm(latGrid,lonGrid,track)
rm(i,long,lati,date)
total <- rbind(total,data2)
rm(data2)

# Hanno
ls()
load("V04.Th11.2006100100.2007033123.Rdata")
i <- match(73,unlist(lapply(track,function(x) x$id)))
str(track[[i]],1)
long <- unlist(lapply(track[i], function(x) x$lon))
lati <- unlist(lapply(track[i], function(x) x$lat))
date <- unlist(lapply(track[i], function(x) x$tim))
data2 <- data.frame(Event = as.integer(14), Name = "Hanno", Time = date, Longitude = long, Latitude = lati)
rm(i,latGrid,lonGrid,track)
rm(long,lati,date)
total <- rbind(total,data2)
rm(data2)

# Kyrill
ls()
load("V04.Th11.2006100100.2007033123.Rdata")
i <- match(77,unlist(lapply(track,function(x) x$id)))
str(track[[i]],1)
long <- unlist(lapply(track[i], function(x) x$lon))
lati <- unlist(lapply(track[i], function(x) x$lat))
date <- unlist(lapply(track[i], function(x) x$tim))
data2 <- data.frame(Event = as.integer(15), Name = "Kyrill", Time = date, Longitude = long, Latitude = lati)
rm(latGrid,lonGrid,track)
rm(i,long,lati,date)
total <- rbind(total,data2)
rm(data2)

# Emma
ls()
load("V04.Th11.2007100100.2008033123.Rdata")
i <- match(85,unlist(lapply(track,function(x) x$id)))
str(track[[i]],1)
long <- unlist(lapply(track[i], function(x) x$lon))
lati <- unlist(lapply(track[i], function(x) x$lat))
date <- unlist(lapply(track[i], function(x) x$tim))
data2 <- data.frame(Event = as.integer(16), Name = "Emma", Time = date, Longitude = long, Latitude = lati)
rm(latGrid,lonGrid,track)
rm(i,long,lati,date)
total <- rbind(total,data2)
rm(data2)

# Klaus
ls()
load("V04.Th11.2008100100.2009033123.Rdata")
i <- match(80,unlist(lapply(track,function(x) x$id)))
str(track[[i]],1)
long <- unlist(lapply(track[i], function(x) x$lon))
lati <- unlist(lapply(track[i], function(x) x$lat))
date <- unlist(lapply(track[i], function(x) x$tim))
data2 <- data.frame(Event = as.integer(17), Name = "Klaus", Time = date, Longitude = long, Latitude = lati)
rm(latGrid,lonGrid,track)
rm(i,long,lati,date)
total <- rbind(total,data2)
rm(data2)

# Janika
ls()
load("V04.Th11.2001100100.2002033123.Rdata")
i <- match(29,unlist(lapply(track,function(x) x$id)))
str(track[[i]],1)
long <- unlist(lapply(track[i], function(x) x$lon))
lati <- unlist(lapply(track[i], function(x) x$lat))
date <- unlist(lapply(track[i], function(x) x$tim))
data2 <- data.frame(Event = as.integer(18), Name = "Janika", Time = date, Longitude = long, Latitude = lati)
rm(latGrid,lonGrid,track)
rm(i,long,lati,date)
total <- rbind(total,data2)
rm(data2)

# Xynthia
ls()
setwd("//Rsgnscsv1/f/Models/ETC/data/ALERT/Xynthia/")
load("V04.Th11.Xynthia.20.ALERT.Rdata")
i <- match(4002,unlist(lapply(track,function(x) x$id)))
str(track[[i]],1)
long <- unlist(lapply(track[i], function(x) x$lon))
lati <- unlist(lapply(track[i], function(x) x$lat))
date <- unlist(lapply(track[i], function(x) x$tim))
data2 <- data.frame(Event = as.integer(19), Name = "Xynthia", Time = date, Longitude = long, Latitude = lati)
rm(latGrid,lonGrid,track,optPar)
rm(i,long,lati,date)
total <- rbind(total,data2)
rm(data2)

setwd("C:/alok/")
write.csv(total, file = "MajorStormLocationInfo.csv", append = FALSE, quote = FALSE, sep = ",",
            eol = "\n", na = "NA", dec = ".", row.names = FALSE,
            col.names = TRUE, qmethod = c("escape", "double"),
            fileEncoding = "")


rm(list=ls())




